openapi: "3.0.0"
info:
  title: "My API"
  version: "1.0"
paths:
  /api/{table_name}:
    get:
      operationId: getTableRecords
      summary: "Fetch all records from a specified table"
      parameters:
        - in: path
          name: table_name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Records fetched successfully"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties: true
        "400":
          description: "Invalid table name"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: "Database error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      operationId: postTableRecord
      summary: "Add a new record to the specified table"
      parameters:
        - in: path
          name: table_name
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        "200":
          description: "Record added successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: "Invalid table name or JSON input"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: "Database error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

servers:
  - url: "http://127.0.0.1:3000"
